language: ruby
env:
  global:
  - TRAVIS_ENV=true
before_install:
  - gem install bundler -v '< 2'
before_script:
script: bundle exec rake
rvm:
  - 2.2.3
gemfile:
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_4.gemfile
sudo: false
cache: bundler
after_success:
  - gem install -q renew_tools --source https://$GEMFURY_API_KEY@gem.fury.io/renewfinancial/
  - renew gem release
